Migrate RocketChat to use RHCC
redhat-cop/pbl-rocketchat pull request #1
Opened 2017-06-20 03:04 UTC by sabre1041

*DO NOT MERGE* - [Bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1462606)

Migrate source of RocketChat to the Red Hat Container Catalog

2017-06-20 03:08 UTC, sabre1041 commented
Until the referenced bug is fixed, the `image` field of the _DeploymentConfig_ can be statically set to `registry.connect.redhat.com/rocketchat/rocketchat:0.56.0`

2017-07-12 17:05 UTC, sabre1041 commented
@etsauer I've updated the PR to use direct reference to the image instead of using ImageStreams.

Please review and merge if applicable

2017-07-20 20:47 UTC, oybed commented
LGTM

2017-07-20 20:48 UTC, oybed approved these changes

2017-07-20 20:50 UTC, oybed commented
@etsauer changes look good to me - please review and merge if you agree

2017-07-21 04:18 UTC, sabre1041 commented
@oybed FYI i made a minor doc fix after you approved the PR.

2017-07-21 15:31 UTC, oybed commented
@sabre1041 still LGTM

2017-07-21 18:50 UTC, etsauer requested changes

2017-07-21 18:50 UTC, etsauer commented on mongodb-statefulset-replication.yaml
> -              volume.alpha.kubernetes.io/storage-class: dynamic
@sabre1041 why are we removing this? i don't see anything in the template or documentation that creates the PV for me.

2017-08-16 12:20 UTC, etsauer approved these changes

2017-08-16 12:20 UTC, merged